import plantCoverImg from '../../../assets/gallery_plant_cover.jpg';
import teamPhotoImg from '../../../assets/gallery_team_photo.jpg';
import dinnerImg from '../../../assets/gallery_dinner.jpg';
import coupleImg from '../../../assets/gallery_couple.jpg';
import editorialModelImg from '../../../assets/gallery_editorial_model.jpg';
import archInteriorImg from '../../../assets/gallery_interior_arch.jpg';

export const designTemplates = [
    {
        id: 'editorial_vogue',
        name: 'Editorial Vogue',
        category: 'Editorial',
        badge: 'Most Popular',
        description: 'Split cover composition with high-fashion serif typography, balanced negative space, and vertical portrait masonry.',
        coverLayout: 'split',
        logo: 'none',
        gridStyle: 'vertical',
        thumbnailSize: 'standard',
        gridSpacing: 'compact',
        fontPreset: 'classic',
        colorPreset: 'air',
        coverImage: editorialModelImg,
        samplePhotos: [editorialModelImg, plantCoverImg, dinnerImg, coupleImg, teamPhotoImg],
    },
    {
        id: 'modern_noir',
        name: 'Modern Noir',
        category: 'Modern',
        badge: 'Trending',
        description: 'Dramatic full-bleed dark vignette with glowing typography, heavy sans display, and expansive panoramic photo cards.',
        coverLayout: 'dark_overlay',
        logo: 'use_logo',
        gridStyle: 'horizontal',
        thumbnailSize: 'large',
        gridSpacing: 'wide',
        fontPreset: 'bold',
        colorPreset: 'graphite',
        coverImage: dinnerImg,
        samplePhotos: [dinnerImg, teamPhotoImg, coupleImg, archInteriorImg, editorialModelImg],
    },
    {
        id: 'fine_art_sage',
        name: 'Fine Art Sage',
        category: 'Fine Art',
        badge: "Editor's Choice",
        description: 'Museum-quality passe-partout matte border framing the photo with warm serif typography and organic botanical sage tones.',
        coverLayout: 'framed',
        logo: 'none',
        gridStyle: 'vertical',
        thumbnailSize: 'standard',
        gridSpacing: 'wide',
        fontPreset: 'soft',
        colorPreset: 'sage',
        coverImage: plantCoverImg,
        samplePhotos: [plantCoverImg, coupleImg, archInteriorImg, editorialModelImg, dinnerImg],
    },
    {
        id: 'golden_dune',
        name: 'Golden Dune',
        category: 'Minimalist',
        badge: 'Warm Aesthetic',
        description: 'Sun-drenched landscape hero image with centered minimalist title below and artisan sand linen palette.',
        coverLayout: 'title_below',
        logo: 'none',
        gridStyle: 'horizontal',
        thumbnailSize: 'standard',
        gridSpacing: 'wide',
        fontPreset: 'minimal',
        colorPreset: 'dune',
        coverImage: coupleImg,
        samplePhotos: [coupleImg, plantCoverImg, archInteriorImg, dinnerImg, teamPhotoImg],
    },
    {
        id: 'coastal_breeze',
        name: 'Coastal Breeze',
        category: 'Fine Art',
        badge: 'Clean & Bright',
        description: 'Airy ocean-inspired layout with clean centered typography above an expansive landscape banner with maritime slate accents.',
        coverLayout: 'title_above',
        logo: 'none',
        gridStyle: 'horizontal',
        thumbnailSize: 'large',
        gridSpacing: 'compact',
        fontPreset: 'simple',
        colorPreset: 'coastal',
        coverImage: archInteriorImg,
        samplePhotos: [archInteriorImg, coupleImg, plantCoverImg, editorialModelImg, dinnerImg],
    },
    {
        id: 'the_atelier',
        name: 'The Atelier',
        category: 'Editorial',
        badge: 'Signature',
        description: 'High-end art magazine journal with asymmetric vertical cover card, issue number metadata, and interactive story button.',
        coverLayout: 'editorial_1',
        logo: 'use_logo',
        gridStyle: 'vertical',
        thumbnailSize: 'standard',
        gridSpacing: 'compact',
        fontPreset: 'classic',
        colorPreset: 'air',
        coverImage: editorialModelImg,
        samplePhotos: [editorialModelImg, plantCoverImg, coupleImg, archInteriorImg, dinnerImg],
    },
    {
        id: 'nordic_journal',
        name: 'Nordic Journal',
        category: 'Minimalist',
        badge: 'Minimalist',
        description: 'Understated Scandinavian aesthetic with lower floating title card and balanced geometric landscape rhythm.',
        coverLayout: 'editorial_2',
        logo: 'none',
        gridStyle: 'horizontal',
        thumbnailSize: 'standard',
        gridSpacing: 'compact',
        fontPreset: 'minimal',
        colorPreset: 'air',
        coverImage: archInteriorImg,
        samplePhotos: [archInteriorImg, dinnerImg, plantCoverImg, teamPhotoImg, coupleImg],
    },
    {
        id: 'glass_contemporary',
        name: 'Contemporary Glass',
        category: 'Modern',
        badge: 'Architectural',
        description: 'Futuristic frosted glass floating title card over full-bleed photography with modern pill actions.',
        coverLayout: 'modern',
        logo: 'use_logo',
        gridStyle: 'horizontal',
        thumbnailSize: 'large',
        gridSpacing: 'wide',
        fontPreset: 'bold',
        colorPreset: 'air',
        coverImage: archInteriorImg,
        samplePhotos: [archInteriorImg, teamPhotoImg, coupleImg, dinnerImg, editorialModelImg],
    },
];

export const fontPresets = {
    simple: {
        title: 'Simple',
        headingFont: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
        bodyFont: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
        headingWeight: '700',
        headingTransform: 'none',
        letterSpacing: '-0.02em',
    },
    classic: {
        title: 'Classic',
        headingFont: "Playfair Display, Georgia, 'Times New Roman', serif",
        bodyFont: "Georgia, serif",
        headingWeight: '400',
        headingTransform: 'uppercase',
        letterSpacing: '0.14em',
    },
    minimal: {
        title: 'Minimal',
        headingFont: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        bodyFont: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        headingWeight: '300',
        headingTransform: 'none',
        letterSpacing: '0.06em',
    },
    soft: {
        title: 'Soft',
        headingFont: "Merriweather, Garamond, Georgia, serif",
        bodyFont: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        headingWeight: '400',
        headingTransform: 'none',
        letterSpacing: '0',
    },
    bold: {
        title: 'Bold',
        headingFont: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        bodyFont: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        headingWeight: '900',
        headingTransform: 'uppercase',
        letterSpacing: '0.08em',
    },
};

export const colorPresets = {
    air: {
        title: 'Air',
        circle1: '#ffffff',
        circle2: '#1f2937',
        bg: '#ffffff',
        text: '#111827',
        textMuted: '#6b7280',
        accent: '#111827',
        cardBg: '#ffffff',
        border: '#e5e7eb',
        btnText: '#ffffff',
        heroBg: '#f9fafb',
    },
    sage: {
        title: 'Sage',
        circle1: '#edf3ef',
        circle2: '#4d6054',
        bg: '#edf3ef',
        text: '#223028',
        textMuted: '#52665a',
        accent: '#37473d',
        cardBg: '#ffffff',
        border: '#d2ded6',
        btnText: '#ffffff',
        heroBg: '#e2ece5',
    },
    dune: {
        title: 'Dune',
        circle1: '#f8f4ee',
        circle2: '#856e58',
        bg: '#f8f4ee',
        text: '#382d23',
        textMuted: '#706051',
        accent: '#524335',
        cardBg: '#ffffff',
        border: '#e6ded3',
        btnText: '#ffffff',
        heroBg: '#f0e8dc',
    },
    coastal: {
        title: 'Coastal',
        circle1: '#f3f6fa',
        circle2: '#536378',
        bg: '#f3f6fa',
        text: '#202d3d',
        textMuted: '#586b82',
        accent: '#32445b',
        cardBg: '#ffffff',
        border: '#dbe3ed',
        btnText: '#ffffff',
        heroBg: '#e7eef7',
    },
    graphite: {
        title: 'Graphite',
        circle1: '#141416',
        circle2: '#2a2b2f',
        bg: '#141416',
        text: '#f9fafb',
        textMuted: '#9ca3af',
        accent: '#ffffff',
        cardBg: '#1f2024',
        border: '#2e3036',
        btnText: '#111827',
        heroBg: '#1c1d22',
    },
};

export const getInitialGalleries = () => [
    {
        id: 'gal-test-1',
        name: '21',
        project: '21',
        shootDate: 'Sep 17, 2026',
        status: 'Published',
        starred: false,
        templateId: 'editorial_vogue',
        coverImage: plantCoverImg,
        plantCover: plantCoverImg,
        design: {
            coverLayout: 'split',
            logo: 'none',
            gridStyle: 'horizontal',
            thumbnailSize: 'standard',
            gridSpacing: 'compact',
            fontPreset: 'simple',
            colorPreset: 'air',
            deviceMode: 'desktop',
        },
        sets: [
            {
                id: 'set-highlights',
                name: 'Highlights',
                items: [
                    { id: 'item-1', url: dinnerImg, title: 'Reception Dinner Banquet', width: 4, height: 3 },
                    { id: 'item-2', url: coupleImg, title: 'Newlyweds Golden Hour', width: 4, height: 3 },
                    { id: 'item-3', url: teamPhotoImg, title: 'Wedding Celebration Guests', width: 16, height: 9 },
                    { id: 'item-4', url: plantCoverImg, title: 'Botanical Floral Details', width: 16, height: 9 },
                    { id: 'item-5', url: editorialModelImg, title: 'Bride Portrait', width: 3, height: 4 },
                    { id: 'item-6', url: archInteriorImg, title: 'Venue Architecture', width: 16, height: 9 },
                ],
            },
            {
                id: 'set-ceremony',
                name: 'Ceremony',
                items: [
                    { id: 'item-7', url: coupleImg, title: 'Exchange of Vows', width: 4, height: 3 },
                    { id: 'item-8', url: teamPhotoImg, title: 'Family Processional', width: 16, height: 9 },
                ],
            },
        ],
        settings: {
            downloadPin: '4829',
            allowHighRes: true,
            requireEmail: false,
            expiryDate: 'Dec 31, 2026',
        },
        activity: [
            { id: 'act-1', text: 'Gallery published and client direct link activated', time: '10 mins ago', type: 'publish' },
            { id: 'act-2', text: 'Invitation email viewed by client (emma@clientstudio.com)', time: '2 hours ago', type: 'email' },
            { id: 'act-3', text: '4 items marked as client favorites', time: 'Yesterday', type: 'favorite' },
        ],
    },
];
